# !pip install -q  tensorflow-datasets

In [1]:
import tensorflow as tf

In [2]:
import tensorflow_datasets as tfds

In [3]:
imdb , info = tfds.load(name="imdb_reviews",with_info=True,as_supervised=True)

In [4]:
import numpy as np

In [5]:
train_data , test_data = imdb['train'],imdb['test']

In [6]:
train_sentence = []
train_label    = []
test_sentence  = []
test_label     = []

for s,l in train_data:
    train_sentence.append(s.numpy())
    train_label.append(l.numpy())
    
for s,l in test_data:
    test_sentence.append(s.numpy())
    test_label.append(l.numpy())

In [7]:
str(train_sentence[0])[2:-1]

'This is a big step down after the surprisingly enjoyable original. This sequel isn\\\'t nearly as fun as part one, and it instead spends too much time on plot development. Tim Thomerson is still the best thing about this series, but his wisecracking is toned down in this entry. The performances are all adequate, but this time the script lets us down. The action is merely routine and the plot is only mildly interesting, so I need lots of silly laughs in order to stay entertained during a "Trancers" movie. Unfortunately, the laughs are few and far between, and so, this film is watchable at best.'

In [8]:
train_label[0]

0

In [9]:
train_label_final = np.array(train_label)
test_label_final  = np.array(test_label)

In [10]:
for i in range(len(test_sentence)):
    test_sentence[i] = str(test_sentence[i])[2:-1]

In [11]:
for i in range(len(train_sentence)):
    train_sentence[i] = str(train_sentence[i])[2:-1]

In [12]:
vocab_size = 10000
emdedding_dim = 16
max_len = 120
trunc_type = 'post'
oov_tok = '<OOV>'

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
tokenizer = Tokenizer(num_words=vocab_size,oov_token=oov_tok)
tokenizer.fit_on_texts(train_sentence)
word_index = tokenizer.word_index
sequence = tokenizer.texts_to_sequences(train_sentence)
padded = pad_sequences(sequence,maxlen=max_len,truncating=trunc_type)

In [15]:
len(sequence[0])

107

In [16]:
test_sequence = tokenizer.texts_to_sequences(test_sentence)
test_padded   = pad_sequences(test_sequence,maxlen=max_len)

In [17]:
model1 = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(vocab_size,emdedding_dim,input_length=max_len),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6,activation="relu"),
    tf.keras.layers.Dense(1,activation="sigmoid")
])

In [18]:
model1.compile(optimizer='adam',loss=tf.keras.losses.binary_crossentropy,metrics=['acc'])

In [19]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 120, 16)           160000    
_________________________________________________________________
flatten (Flatten)            (None, 1920)              0         
_________________________________________________________________
dense (Dense)                (None, 6)                 11526     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 7         
Total params: 171,533
Trainable params: 171,533
Non-trainable params: 0
_________________________________________________________________


In [20]:
history = model1.fit(padded,train_label_final,epochs=10,validation_data=(test_padded,test_label_final))

Train on 25000 samples, validate on 25000 samples
Epoch 1/10
25000/25000 [==============================] - ETA: 23:26 - loss: 0.6871 - acc: 0.62 - ETA: 2:59 - loss: 0.6949 - acc: 0.5000 - ETA: 1:44 - loss: 0.6941 - acc: 0.504 - ETA: 1:14 - loss: 0.6943 - acc: 0.504 - ETA: 58s - loss: 0.6942 - acc: 0.495 - ETA: 45s - loss: 0.6938 - acc: 0.50 - ETA: 40s - loss: 0.6939 - acc: 0.49 - ETA: 37s - loss: 0.6938 - acc: 0.50 - ETA: 33s - loss: 0.6936 - acc: 0.50 - ETA: 30s - loss: 0.6932 - acc: 0.51 - ETA: 27s - loss: 0.6927 - acc: 0.51 - ETA: 25s - loss: 0.6930 - acc: 0.51 - ETA: 23s - loss: 0.6929 - acc: 0.51 - ETA: 22s - loss: 0.6927 - acc: 0.51 - ETA: 20s - loss: 0.6925 - acc: 0.51 - ETA: 19s - loss: 0.6924 - acc: 0.52 - ETA: 18s - loss: 0.6923 - acc: 0.52 - ETA: 18s - loss: 0.6925 - acc: 0.51 - ETA: 18s - loss: 0.6925 - acc: 0.51 - ETA: 18s - loss: 0.6924 - acc: 0.51 - ETA: 18s - loss: 0.6923 - acc: 0.51 - ETA: 18s - loss: 0.6923 - acc: 0.51 - ETA: 17s - loss: 0.6921 - acc: 0.52 - ETA: 16s

25000/25000 [==============================] - ETA: 8s - loss: 0.2439 - acc: 0.937 - ETA: 6s - loss: 0.2380 - acc: 0.925 - ETA: 6s - loss: 0.2360 - acc: 0.918 - ETA: 7s - loss: 0.2302 - acc: 0.922 - ETA: 7s - loss: 0.2301 - acc: 0.923 - ETA: 8s - loss: 0.2314 - acc: 0.922 - ETA: 10s - loss: 0.2329 - acc: 0.91 - ETA: 11s - loss: 0.2403 - acc: 0.91 - ETA: 11s - loss: 0.2416 - acc: 0.91 - ETA: 10s - loss: 0.2378 - acc: 0.91 - ETA: 10s - loss: 0.2369 - acc: 0.91 - ETA: 9s - loss: 0.2384 - acc: 0.9171 - ETA: 9s - loss: 0.2392 - acc: 0.916 - ETA: 8s - loss: 0.2362 - acc: 0.916 - ETA: 8s - loss: 0.2397 - acc: 0.913 - ETA: 8s - loss: 0.2409 - acc: 0.911 - ETA: 9s - loss: 0.2452 - acc: 0.910 - ETA: 9s - loss: 0.2460 - acc: 0.909 - ETA: 10s - loss: 0.2453 - acc: 0.90 - ETA: 10s - loss: 0.2457 - acc: 0.90 - ETA: 10s - loss: 0.2435 - acc: 0.91 - ETA: 9s - loss: 0.2398 - acc: 0.9134 - ETA: 9s - loss: 0.2439 - acc: 0.912 - ETA: 9s - loss: 0.2433 - acc: 0.912 - ETA: 9s - loss: 0.2414 - acc: 0.913 - E

25000/25000 [==============================] - ETA: 8s - loss: 0.0553 - acc: 1.000 - ETA: 6s - loss: 0.1109 - acc: 0.976 - ETA: 6s - loss: 0.1100 - acc: 0.975 - ETA: 5s - loss: 0.1116 - acc: 0.973 - ETA: 6s - loss: 0.1052 - acc: 0.975 - ETA: 6s - loss: 0.1021 - acc: 0.978 - ETA: 6s - loss: 0.1043 - acc: 0.979 - ETA: 6s - loss: 0.1032 - acc: 0.979 - ETA: 6s - loss: 0.1035 - acc: 0.978 - ETA: 6s - loss: 0.1045 - acc: 0.977 - ETA: 6s - loss: 0.1035 - acc: 0.978 - ETA: 6s - loss: 0.1069 - acc: 0.978 - ETA: 6s - loss: 0.1057 - acc: 0.978 - ETA: 6s - loss: 0.1056 - acc: 0.978 - ETA: 6s - loss: 0.1073 - acc: 0.977 - ETA: 6s - loss: 0.1065 - acc: 0.977 - ETA: 6s - loss: 0.1081 - acc: 0.975 - ETA: 6s - loss: 0.1097 - acc: 0.974 - ETA: 6s - loss: 0.1095 - acc: 0.974 - ETA: 6s - loss: 0.1086 - acc: 0.975 - ETA: 6s - loss: 0.1073 - acc: 0.975 - ETA: 6s - loss: 0.1063 - acc: 0.975 - ETA: 6s - loss: 0.1056 - acc: 0.974 - ETA: 6s - loss: 0.1071 - acc: 0.974 - ETA: 5s - loss: 0.1069 - acc: 0.974 - ETA

25000/25000 [==============================] - ETA: 5s - loss: 0.0393 - acc: 1.000 - ETA: 5s - loss: 0.0319 - acc: 0.996 - ETA: 5s - loss: 0.0268 - acc: 0.997 - ETA: 5s - loss: 0.0248 - acc: 0.998 - ETA: 5s - loss: 0.0292 - acc: 0.997 - ETA: 5s - loss: 0.0293 - acc: 0.998 - ETA: 5s - loss: 0.0286 - acc: 0.998 - ETA: 5s - loss: 0.0285 - acc: 0.998 - ETA: 5s - loss: 0.0276 - acc: 0.998 - ETA: 5s - loss: 0.0267 - acc: 0.998 - ETA: 6s - loss: 0.0263 - acc: 0.998 - ETA: 5s - loss: 0.0258 - acc: 0.998 - ETA: 5s - loss: 0.0274 - acc: 0.998 - ETA: 5s - loss: 0.0267 - acc: 0.998 - ETA: 5s - loss: 0.0266 - acc: 0.997 - ETA: 5s - loss: 0.0261 - acc: 0.998 - ETA: 5s - loss: 0.0258 - acc: 0.998 - ETA: 5s - loss: 0.0276 - acc: 0.997 - ETA: 5s - loss: 0.0272 - acc: 0.997 - ETA: 5s - loss: 0.0268 - acc: 0.998 - ETA: 5s - loss: 0.0276 - acc: 0.997 - ETA: 5s - loss: 0.0273 - acc: 0.998 - ETA: 5s - loss: 0.0270 - acc: 0.997 - ETA: 5s - loss: 0.0268 - acc: 0.998 - ETA: 4s - loss: 0.0266 - acc: 0.997 - ETA

25000/25000 [==============================] - ETA: 10s - loss: 0.0077 - acc: 1.00 - ETA: 6s - loss: 0.0240 - acc: 0.9961 - ETA: 5s - loss: 0.0153 - acc: 0.998 - ETA: 5s - loss: 0.0191 - acc: 0.997 - ETA: 5s - loss: 0.0158 - acc: 0.998 - ETA: 5s - loss: 0.0137 - acc: 0.998 - ETA: 5s - loss: 0.0124 - acc: 0.998 - ETA: 5s - loss: 0.0170 - acc: 0.997 - ETA: 5s - loss: 0.0156 - acc: 0.997 - ETA: 5s - loss: 0.0148 - acc: 0.998 - ETA: 5s - loss: 0.0140 - acc: 0.998 - ETA: 5s - loss: 0.0133 - acc: 0.998 - ETA: 5s - loss: 0.0136 - acc: 0.998 - ETA: 5s - loss: 0.0131 - acc: 0.998 - ETA: 5s - loss: 0.0127 - acc: 0.998 - ETA: 4s - loss: 0.0122 - acc: 0.998 - ETA: 4s - loss: 0.0119 - acc: 0.998 - ETA: 4s - loss: 0.0116 - acc: 0.998 - ETA: 4s - loss: 0.0112 - acc: 0.998 - ETA: 4s - loss: 0.0109 - acc: 0.998 - ETA: 4s - loss: 0.0107 - acc: 0.998 - ETA: 4s - loss: 0.0113 - acc: 0.998 - ETA: 4s - loss: 0.0111 - acc: 0.998 - ETA: 4s - loss: 0.0108 - acc: 0.998 - ETA: 4s - loss: 0.0106 - acc: 0.998 - ET

25000/25000 [==============================] - ETA: 3s - loss: 0.0024 - acc: 1.000 - ETA: 5s - loss: 0.0034 - acc: 1.000 - ETA: 5s - loss: 0.0032 - acc: 1.000 - ETA: 5s - loss: 0.0032 - acc: 1.000 - ETA: 5s - loss: 0.0032 - acc: 1.000 - ETA: 5s - loss: 0.0031 - acc: 1.000 - ETA: 5s - loss: 0.0031 - acc: 1.000 - ETA: 5s - loss: 0.0030 - acc: 1.000 - ETA: 5s - loss: 0.0029 - acc: 1.000 - ETA: 5s - loss: 0.0030 - acc: 1.000 - ETA: 5s - loss: 0.0030 - acc: 1.000 - ETA: 5s - loss: 0.0029 - acc: 1.000 - ETA: 5s - loss: 0.0029 - acc: 1.000 - ETA: 5s - loss: 0.0029 - acc: 1.000 - ETA: 5s - loss: 0.0028 - acc: 1.000 - ETA: 4s - loss: 0.0033 - acc: 0.999 - ETA: 4s - loss: 0.0032 - acc: 0.999 - ETA: 4s - loss: 0.0032 - acc: 0.999 - ETA: 4s - loss: 0.0042 - acc: 0.999 - ETA: 4s - loss: 0.0041 - acc: 0.999 - ETA: 4s - loss: 0.0040 - acc: 0.999 - ETA: 4s - loss: 0.0040 - acc: 0.999 - ETA: 4s - loss: 0.0039 - acc: 0.999 - ETA: 4s - loss: 0.0039 - acc: 0.999 - ETA: 4s - loss: 0.0038 - acc: 0.999 - ETA

25000/25000 [==============================] - ETA: 4s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0018 - acc: 1.000 - ETA: 5s - loss: 0.0016 - acc: 1.000 - ETA: 5s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0016 - acc: 1.000 - ETA: 5s - loss: 0.0017 - acc: 1.000 - ETA: 5s - loss: 0.0017 - acc: 1.000 - ETA: 5s - loss: 0.0017 - acc: 1.000 - ETA: 5s - loss: 0.0016 - acc: 1.000 - ETA: 5s - loss: 0.0016 - acc: 1.000 - ETA: 5s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0015 - acc: 1.000 - ETA: 5s - loss: 0.0014 - acc: 1.000 - ETA: 5s - loss: 0.0014 - acc: 1.000 - ETA: 5s - loss: 0.0014 - acc: 1.000 - ETA: 5s - loss: 0.0014 - acc: 1.000 - ETA: 5s - loss: 0.0014 - acc: 1.000 - ETA: 4s - loss: 0.0014 - acc: 1.000 - ETA: 4s - loss: 0.0014 - acc: 1.000 - ETA: 4s - loss: 0.0014 - acc: 1.000 - ETA: 4s - loss: 0.0014 - acc: 1.000 - ETA: 4s - loss: 0.0014 - acc: 1.000 - ETA

25000/25000 [==============================] - ETA: 11s - loss: 0.0012 - acc: 1.00 - ETA: 8s - loss: 7.2129e-04 - acc: 1.000 - ETA: 7s - loss: 7.5606e-04 - acc: 1.000 - ETA: 7s - loss: 7.8759e-04 - acc: 1.000 - ETA: 7s - loss: 7.3538e-04 - acc: 1.000 - ETA: 7s - loss: 7.2543e-04 - acc: 1.000 - ETA: 8s - loss: 7.0667e-04 - acc: 1.000 - ETA: 8s - loss: 7.0209e-04 - acc: 1.000 - ETA: 8s - loss: 6.8517e-04 - acc: 1.000 - ETA: 7s - loss: 6.8232e-04 - acc: 1.000 - ETA: 7s - loss: 6.8674e-04 - acc: 1.000 - ETA: 7s - loss: 6.7988e-04 - acc: 1.000 - ETA: 7s - loss: 6.8685e-04 - acc: 1.000 - ETA: 7s - loss: 6.8336e-04 - acc: 1.000 - ETA: 7s - loss: 6.7546e-04 - acc: 1.000 - ETA: 7s - loss: 6.6938e-04 - acc: 1.000 - ETA: 7s - loss: 6.7011e-04 - acc: 1.000 - ETA: 7s - loss: 6.6258e-04 - acc: 1.000 - ETA: 7s - loss: 6.7254e-04 - acc: 1.000 - ETA: 7s - loss: 6.6937e-04 - acc: 1.000 - ETA: 7s - loss: 6.6472e-04 - acc: 1.000 - ETA: 7s - loss: 6.6556e-04 - acc: 1.000 - ETA: 6s - loss: 6.6307e-04 - acc:

25000/25000 [==============================] - ETA: 10s - loss: 5.3833e-04 - acc: 1.00 - ETA: 6s - loss: 3.1061e-04 - acc: 1.0000 - ETA: 5s - loss: 3.2158e-04 - acc: 1.000 - ETA: 5s - loss: 3.2898e-04 - acc: 1.000 - ETA: 5s - loss: 3.2315e-04 - acc: 1.000 - ETA: 5s - loss: 3.3128e-04 - acc: 1.000 - ETA: 5s - loss: 3.4125e-04 - acc: 1.000 - ETA: 5s - loss: 3.5163e-04 - acc: 1.000 - ETA: 5s - loss: 3.5267e-04 - acc: 1.000 - ETA: 5s - loss: 3.6010e-04 - acc: 1.000 - ETA: 5s - loss: 3.6378e-04 - acc: 1.000 - ETA: 5s - loss: 3.5696e-04 - acc: 1.000 - ETA: 5s - loss: 3.5414e-04 - acc: 1.000 - ETA: 5s - loss: 3.4872e-04 - acc: 1.000 - ETA: 5s - loss: 3.4856e-04 - acc: 1.000 - ETA: 5s - loss: 3.4896e-04 - acc: 1.000 - ETA: 5s - loss: 3.5133e-04 - acc: 1.000 - ETA: 5s - loss: 3.4772e-04 - acc: 1.000 - ETA: 5s - loss: 3.4571e-04 - acc: 1.000 - ETA: 4s - loss: 3.4835e-04 - acc: 1.000 - ETA: 4s - loss: 3.4484e-04 - acc: 1.000 - ETA: 4s - loss: 3.4565e-04 - acc: 1.000 - ETA: 4s - loss: 3.4559e-04 -

25000/25000 [==============================] - ETA: 5s - loss: 2.5914e-04 - acc: 1.000 - ETA: 5s - loss: 1.9784e-04 - acc: 1.000 - ETA: 5s - loss: 1.8739e-04 - acc: 1.000 - ETA: 5s - loss: 1.7693e-04 - acc: 1.000 - ETA: 5s - loss: 1.7979e-04 - acc: 1.000 - ETA: 5s - loss: 1.8860e-04 - acc: 1.000 - ETA: 5s - loss: 1.9096e-04 - acc: 1.000 - ETA: 5s - loss: 1.9159e-04 - acc: 1.000 - ETA: 5s - loss: 1.9565e-04 - acc: 1.000 - ETA: 5s - loss: 1.9080e-04 - acc: 1.000 - ETA: 5s - loss: 1.9180e-04 - acc: 1.000 - ETA: 5s - loss: 1.9243e-04 - acc: 1.000 - ETA: 5s - loss: 1.9047e-04 - acc: 1.000 - ETA: 5s - loss: 1.9436e-04 - acc: 1.000 - ETA: 5s - loss: 1.9571e-04 - acc: 1.000 - ETA: 5s - loss: 1.9622e-04 - acc: 1.000 - ETA: 4s - loss: 1.9516e-04 - acc: 1.000 - ETA: 4s - loss: 1.9558e-04 - acc: 1.000 - ETA: 4s - loss: 1.9576e-04 - acc: 1.000 - ETA: 4s - loss: 1.9491e-04 - acc: 1.000 - ETA: 4s - loss: 1.9288e-04 - acc: 1.000 - ETA: 4s - loss: 1.9206e-04 - acc: 1.000 - ETA: 4s - loss: 1.9279e-04 - 

In [21]:
weights = model1.layers[0].get_weights()[0]

In [22]:
weights.shape

(10000, 16)

In [23]:
reverse_word_index = dict([(value,key) for (key,value) in word_index.items()])

In [24]:
import io

In [25]:
out_v = io.open("vecs.tsv","w",encoding='utf-8')
out_m = io.open("meta.tsv","w",encoding='utf-8')

In [26]:
for word_num in range(1,vocab_size):
    word = reverse_word_index[word_num]
    embedding = weights[word_num]
    out_m.write(word+'\n')
    out_v.write('\t'.join([str(x) for x in embedding]) + '\n')
out_m.close()
out_v.close()

In [27]:
weights[0]

array([-0.00716579,  0.11808513,  0.01629731,  0.04574597,  0.01705289,
       -0.02778289, -0.02130054,  0.03049744, -0.00821611, -0.03973374,
       -0.07429357, -0.00924375, -0.01466185, -0.01080307,  0.11026341,
       -0.02700664], dtype=float32)

In [28]:
reverse_word_index[5]

'of'

In [29]:
len(word_index)

84459

In [30]:
sen = ["i am ankit","hi there"]
tk = Tokenizer(3)

In [31]:
tk.fit_on_texts(sen)
print(tk.word_index)

{'i': 1, 'am': 2, 'ankit': 3, 'hi': 4, 'there': 5}


In [32]:
tk.texts_to_sequences(sen)

[[1, 2], []]

In [33]:
test_label_final

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [36]:
model1.predict_classes(test_padded[0:1])

array([[1]])